### ISSUE TITLE
reading of TileDirectory with custom grid fails

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#162]
```yaml
pyramid:
    grid:
        shape: [161, 315]
        bounds: [141920, 89840, 948320, 502000]
        is_global: False
        epsg: 31259
```
