### ISSUE TITLE
Change tile order z/y/x to z/x/y

### ISSUE THREAD

**Issue by normanb** [ungarj/mapchete#668]
Not an issue but a question (in the absence of a mailing list).

I can use Z/Y/Z for vector output in a web browser (and it works great, thank you!) by specifying this in a tile.json file, but I want to conform more to web maps using vectors (e.g. Mapbox and others) I would use Z/X/Y, is there a way to change the output and if not where should I look in the code to make this change?

Thanks!

**Comment by ungarj** [comment]
Yes, you can set it via the `tile_path_schema` parameter in the output definition:

```yaml
output:
  format: foo
  path: bar
  tile_path_schema: {zoom}/{col}/{row}.{extension}
```
(default it is set as `{zoom}/{row}/{col}.{extension}`)
