### ISSUE TITLE
Off by one zoom level

### ISSUE THREAD

**Issue by normanb** [ungarj/mapchete#669]
I am processing DEMs at zoom level 14. I print the following in my processing function;

```
print(f"res {dem.tile.transform}")
```

with a definition of 

```
zoom_levels: 14

pyramid:
    grid: mercator
    pixelbuffer: 2
    metatiling: 1
```

And I see 

```
| 0.00,-9.55, 4752567.78|
| 0.00, 0.00, 1.00|
```

So a pixel size of ~9.55 metre which is zoom level 13 at the equator if I am following https://docs.mapbox.com/help/glossary/zoom-level/

It seems that the zoom level reading is off by one. Also if I am reading at higher latitudes then this should change to be more like 3.6 metre per pixel at zoom level 14.
