### ISSUE TITLE
Tiles are completely different the first time they are loaded

### ISSUE THREAD

**Issue by dzfranklin** [ungarj/mapchete#672]
The first time I load a tile I see something complete different from every subsequent load.

```yaml
process: hillshade.py
zoom_levels:
    min: 8
    max: 12
input:
    dem: copernicus_dem_30m_pentlands_sample.tif
output:
    format: PNG_hillshade
    path: /out
    pixelbuffer: 0
pyramid:
    grid: mercator
process_parameters:
    resampling: bilinear
```

```python
def execute(mp, resampling):
    with mp.open("dem") as src:
        if src.is_empty(1):
            return "empty"
        else:
            return src.read(1, resampling=resampling)
```

First load:

![Image](https://github.com/user-attachments/assets/1da629ac-52bc-4e7f-ace6-e51141f71a76)

Subsequent loads:

![Image](https://github.com/user-attachments/assets/0b823732-fba7-4e35-bcb2-78e19fbe7695)

I am using mapchete 2025.1.1 installed via pip. I made a script that reproduces the issue in a docker container: https://github.com/dzfranklin/mapchete-inconsistent-repro

The tile written to the output directory matches the first load. I am not sure if the first load is completely correct but it looks closer to the correct hillshading than the second load.
