### ISSUE TITLE
directory with tiles as input option

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#89]
Add an abstract input type where a directory (e.g. a written output from another mapchete process) can be provided.

e.g.:
```yaml
input:
  dir_input:
    format: TileDir
    path: /path/to/dir
    metatiling: 2
    type: geodetic
    bounds: # optional    
```

Should also work for remote "directories" like tiled data on an object store accessible via HTTP.
